%Illustration of various activation function used in Neural Networks
clc; clear all;
x=-10:0.1:10;
tmp=exp(-x);
y1=1./(1+tmp);
y2=(1-tmp)./(1+tmp);
y3=-x;
y4=tanh(x);
subplot(221);
plot(x,y1);
grid on;
axis([min(x), max(x), -2, 2]);
title('Sigmoid function');
xlabel('(a)');
subplot(222);
plot(x,y2);
grid on;
axis([min(x), max(x), -2, 2]);
title('Hyperbolic function');
xlabel('(b)');
subplot(223);
plot(x,y3);
grid on;
axis([min(x), max(x), -2, 2]);
title('Identity Function');
xlabel('(c)');
subplot(224);
plot(x,y4);
grid on;
axis([min(x), max(x), -2, 2]);
title('Tanh function');
xlabel('(d)');
